---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Pull Request

on:
  pull_request:
    branches: ["main"]
    paths: ["charts/**/metadata.yaml"]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Get Changed Files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@b1144fc772fca235a50902c7bb6cc431cc7d8e27 # v0.3.2
        with:
          patterns: charts/**/metadata.yaml

  changed:
    if: ${{ needs.prepare.outputs.changed-files != '[]' }}
    needs: ["prepare"]
    name: Get Changed Charts
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.charts.outputs.charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Extract Chart values
        id: charts
        run: |
          charts=$(yq eval-all --indent=0 --output-format=json "[.]" ${{ join(fromJSON(needs.prepare.outputs.changed-files), ' ') }})
          echo "charts=${charts}" >> $GITHUB_OUTPUT

  build:
    if: ${{ needs.changed.outputs.charts != '[]' }}
    needs: ["changed"]
    name: Build ${{ matrix.chart.name }}
    uses: ./.github/workflows/chart-builder.yaml
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        chart: ${{ fromJSON(needs.changed.outputs.charts) }}
      fail-fast: false
      max-parallel: 4
    with:
      name: ${{ matrix.chart.name }}
      version: ${{ matrix.chart.version }}
      registry: ${{ matrix.chart.registry }}
      release: false

  status:
    if: ${{ !cancelled() }}
    needs: ["build"]
    name: Build Success
    runs-on: ubuntu-latest
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed or skipped?
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
